# AsliKaam V1 — industry content data
# Every entry defaults to "proposed" per the honesty rule (no delivered pilot on record yet).
# Flip an entry's "badge" to "proven" once a real pilot has actually run in that vertical.

BRAND = "AsliKaam"
TAGLINE = "Digital Partner of MSMEs Automation"
WHATSAPP_NUMBER = "911234567890"  # TODO: replace with the real WhatsApp Business number before launch
PHONE_NUMBER = "+91 12345 67890"  # TODO: replace with the real business line before launch

NAV = [
    ("Home", "/"),
    ("Industries", "/industries/"),
    ("Blogs", "/blogs/"),
    ("Demos", "/demos/"),
    ("Agentic Use Cases", "/agentic-use-cases/"),
    ("Pricing", "/pricing/"),
]

INDUSTRIES = [
    {
        "slug": "export-trading",
        "name": "Export / Trading",
        "icon": "🚢",
        "badge": "proposed",
        "use_case": "A buyer messages for price and sample. No reply for 2 days. They move on to the next supplier in the search results.",
        "solution": "Catalog + WhatsApp RFQ routing, same-day quote",
        "solution_bullets": [
            "Product catalog with landed-cost-ready specs, always live",
            "Every inquiry auto-routed to WhatsApp with the right person tagged",
            "Quote templates so a same-day reply is the default, not the exception",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "RFQ sits unread for 2 days",
        "citation": {
            "stat": "India's share of global apparel, textile, leather and footwear exports slipped from a 2013 peak of 4.5% to 3.5% by 2022, as Bangladesh (5.1%) and Vietnam (5.9%) pulled ahead — a gap the World Bank links partly to lower digital adoption in these sectors.",
            "source": "Deccan Herald, citing World Bank",
            "url": "https://www.deccanherald.com/amp/story/business%2Feconomy%2Findia-losing-to-smaller-rivals-like-bangladesh-and-vietnam-in-manufacturing-world-bank-says-3176072",
        },
        "pain": {
            "eyebrow": "The Moment",
            "title": "“Price + sample, please.”",
            "body": "A genuine buyer inquiry lands in the inbox. Nobody's watching it today.",
            "chat": [
                ("in", "Hi, interested in your product. Can you share price + sample?"),
                ("meta", "Seen · 2 days ago"),
                ("in", "Following up — found another supplier, thanks anyway."),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Same inquiry, same day",
            "body": "The RFQ is routed straight to WhatsApp the moment it lands, with a quote template ready to go.",
            "chat": [
                ("in", "Hi, interested in your product. Can you share price + sample?"),
                ("out", "Thanks for reaching out! Here's our catalog + a quote for your quantity 👇"),
                ("out", "Sample dispatch confirmed — tracking shared shortly."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "One fast reply, compounding",
            "body": "Same-day response rate turns cold leads into repeat buyers across every inquiry channel.",
            "stat_label": "Quote turnaround",
            "stat_from": "4 days",
            "stat_to": "Same day",
        },
    },
    {
        "slug": "hospital",
        "name": "Hospital (multi-branch)",
        "icon": "🏥",
        "badge": "proposed",
        "use_case": "A new branch opens. Zero walk-ins. It's invisible on Google Search and Maps.",
        "solution": "Per-branch GBP + doctor pages + WhatsApp appointments",
        "solution_bullets": [
            "A dedicated Google Business Profile for every branch, not just HQ",
            "Individual doctor pages so patients can find and pick by specialty",
            "WhatsApp appointment booking with automatic confirmations",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "New branch invisible on Google",
        "citation": {
            "stat": "Insured patients are increasingly choosing corporate hospitals for standardized, cashless care — a shift KPMG says is driving standalone and single-region hospitals to fold into larger regional chains across Tier 2/3 cities.",
            "source": "KPMG India",
            "url": "https://kpmg.com/in/en/insights/2025/12/multi-speciality-hospitals-in-india-evolution-of-hospitals-deals-post-covid.html",
        },
        "pain": {
            "eyebrow": "The Moment",
            "title": "A branch that doesn't exist online",
            "body": "The new branch is open for business. Google Maps still doesn't know it.",
            "chat": [
                ("in", "Is there a branch near Wakad? Can't find it on Maps."),
                ("meta", "No reply · branch has no listing"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Findable, then bookable",
            "body": "Every branch gets its own listing, doctor pages, and a WhatsApp line for appointments.",
            "chat": [
                ("in", "Is there a branch near Wakad?"),
                ("out", "Yes! Wakad branch, open 9am–9pm. Book your slot here 👇"),
                ("out", "Appointment confirmed for Dr. Mehta, Thursday 5:30pm."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Every branch, findable",
            "body": "Each new location goes live on Google and WhatsApp on day one instead of month three.",
            "stat_label": "Branches visible on Google",
            "stat_from": "1 of 5",
            "stat_to": "5 of 5",
        },
    },
    {
        "slug": "coaching-institute",
        "name": "Coaching Institute",
        "icon": "🎓",
        "badge": "proposed",
        "use_case": "A student outside the city wants the recorded batch. There's no way for them to actually buy it.",
        "solution": "Course sales page + payment + auto access",
        "solution_bullets": [
            "A course sales page that explains the batch and its outcomes",
            "Payment collection built in — no separate link juggling",
            "Access granted automatically the moment payment clears",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Out-of-city students can't buy",
        "pain": {
            "eyebrow": "The Moment",
            "title": "“How do I join from outside the city?”",
            "body": "Interest is real. The buying path doesn't exist yet.",
            "chat": [
                ("in", "I'm from Nagpur, can I get the recorded batch?"),
                ("meta", "Seen · no payment link · lead goes cold"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Pay, then learn — same minute",
            "body": "A sales page and checkout mean any student, anywhere, can enrol immediately.",
            "chat": [
                ("in", "I'm from Nagpur, can I get the recorded batch?"),
                ("out", "Yes! Enrol here — instant access after payment 👇"),
                ("out", "Payment received. Your batch access is live now."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "One city becomes every city",
            "body": "The same batch now sells itself to students the classroom could never reach.",
            "stat_label": "Addressable students",
            "stat_from": "1 city",
            "stat_to": "Anywhere",
        },
    },
    {
        "slug": "real-estate-developer",
        "name": "Real Estate Developer",
        "icon": "🏢",
        "badge": "proposed",
        "use_case": "A portal lead comes in. Follow-up happens 3 days later. By then the lead has gone cold.",
        "solution": "Microsite + WhatsApp capture + auto brochure/visit booking",
        "solution_bullets": [
            "A project microsite that captures intent the moment someone lands",
            "Instant WhatsApp follow-up — no 3-day gap",
            "Auto-sent brochure and one-tap site-visit booking",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "3-day follow-up delay",
        "pain": {
            "eyebrow": "The Moment",
            "title": "A hot lead, cooling for 3 days",
            "body": "The portal inquiry is in the CRM. Nobody calls back until it's too late.",
            "chat": [
                ("in", "Interested in the 2BHK. Send details?"),
                ("meta", "3 days later — “Already booked elsewhere, thanks.”"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Brochure in, visit booked, same hour",
            "body": "The microsite captures the lead and WhatsApp does the follow-up instantly.",
            "chat": [
                ("in", "Interested in the 2BHK. Send details?"),
                ("out", "Here's the brochure + floor plan 👇 Want to book a site visit?"),
                ("out", "Visit confirmed: Saturday 11am."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Every lead, followed up on day one",
            "body": "The 3-day gap closes to minutes, across every project and every portal.",
            "stat_label": "Follow-up time",
            "stat_from": "3 days",
            "stat_to": "Minutes",
        },
    },
    {
        "slug": "b2b-manufacturer",
        "name": "B2B Manufacturer",
        "icon": "🏭",
        "badge": "proposed",
        "use_case": "An RFQ finally gets quoted — 4 days late. The order is already gone.",
        "solution": "Catalog + inquiry-to-WhatsApp + fast quote templates",
        "solution_bullets": [
            "A live catalog buyers can browse and reference in their RFQ",
            "Every inquiry pushed straight to WhatsApp, not lost in email",
            "Pre-built quote templates so pricing goes out same-day",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "RFQ quoted 4 days late",
        "pain": {
            "eyebrow": "The Moment",
            "title": "4 days to a quote — order's gone",
            "body": "The RFQ sat in a shared inbox. By the time it's quoted, the buyer bought elsewhere.",
            "chat": [
                ("in", "Need a quote for 5000 units, urgent."),
                ("meta", "Quoted 4 days later — order already placed with competitor"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Quote out before the buyer moves on",
            "body": "The inquiry routes to WhatsApp instantly, template quote follows within hours.",
            "chat": [
                ("in", "Need a quote for 5000 units, urgent."),
                ("out", "On it — quote attached, valid 7 days 👇"),
                ("out", "PO received, production scheduling confirmed."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Speed becomes the pitch",
            "body": "Buyers start choosing the fastest quote — which is now always this one.",
            "stat_label": "Quote turnaround",
            "stat_from": "4 days",
            "stat_to": "Hours",
        },
    },
    {
        "slug": "private-school",
        "name": "Private School",
        "icon": "🏫",
        "badge": "proposed",
        "use_case": "Admission week. The phone line is jammed. Enrollments are lost to the school that answered.",
        "solution": "Admission capture + WhatsApp auto-response + GBP",
        "solution_bullets": [
            "An admission-enquiry form that never goes to a busy line",
            "Instant WhatsApp auto-response with next steps",
            "A Google Business Profile parents actually find during search",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Jammed phone line, admission week",
        "pain": {
            "eyebrow": "The Moment",
            "title": "Busy tone, during admission week",
            "body": "A parent calls three times. Every time, the line is busy. They call another school.",
            "chat": [
                ("in", "Calling about Grade 2 admission..."),
                ("meta", "Line busy × 3 — parent enrolls elsewhere"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Never a busy line again",
            "body": "The enquiry form and WhatsApp auto-response pick up exactly when the phone can't.",
            "chat": [
                ("in", "Interested in Grade 2 admission."),
                ("out", "Thanks for reaching out! Here's the admission process + form 👇"),
                ("out", "Form received — counsellor will call within the hour."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Admission week, without the chaos",
            "body": "Every enquiry gets captured, whether the line is free or not.",
            "stat_label": "Enquiries captured",
            "stat_from": "Missed calls",
            "stat_to": "100% logged",
        },
    },
    {
        "slug": "diagnostic-lab",
        "name": "Diagnostic Lab",
        "icon": "🧪",
        "badge": "proposed",
        "use_case": "Home-collection booking has too much friction. The rival lab down the road wins the sample.",
        "solution": "Per-branch GBP + WhatsApp booking + digital reports",
        "solution_bullets": [
            "Google presence for every branch so nearby patients find you first",
            "WhatsApp booking for home collection in under a minute",
            "Digital reports delivered where the patient already is — WhatsApp",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Booking friction loses the sample",
        "pain": {
            "eyebrow": "The Moment",
            "title": "Too many steps to book a test",
            "body": "The patient wants a home-collection blood test. The booking process asks for too much, too slowly.",
            "chat": [
                ("in", "Need a home blood test tomorrow morning."),
                ("meta", "No response · patient books with the lab next door"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Booked in one WhatsApp message",
            "body": "Slot, address, and confirmation — all inside the same chat the patient already opened.",
            "chat": [
                ("in", "Need a home blood test tomorrow morning."),
                ("out", "Booked! Technician arrives 8–9am. Report on WhatsApp by evening 👇"),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "The nearest lab, and the easiest one",
            "body": "Being both visible and frictionless wins the sample before the rival even replies.",
            "stat_label": "Booking time",
            "stat_from": "Multi-step form",
            "stat_to": "One chat",
        },
    },
    {
        "slug": "wedding-planner-banquet",
        "name": "Wedding Planner / Banquet",
        "icon": "✨",
        "badge": "proposed",
        "use_case": "A high-value Instagram DM about a wedding date arrives — and gets buried under everything else. Never answered.",
        "solution": "Proof-of-work site + WhatsApp date/quote flow",
        "solution_bullets": [
            "A portfolio site that shows real work, not just a feed",
            "Every inquiry routed to WhatsApp for date and quote conversations",
            "Nothing high-value gets buried in a DM inbox again",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "High-value DM buried, never answered",
        "pain": {
            "eyebrow": "The Moment",
            "title": "A ₹8L booking, sitting in DMs",
            "body": "The inquiry is real and urgent. It's competing with a hundred comments and never surfaces.",
            "chat": [
                ("in", "Loved your work! Available for Dec 14 wedding, 300 guests?"),
                ("meta", "Buried in DMs · unanswered for a week"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Straight to WhatsApp, same day",
            "body": "The portfolio site routes every serious inquiry to a real conversation, immediately.",
            "chat": [
                ("in", "Available for Dec 14 wedding, 300 guests?"),
                ("out", "Yes! Here's our portfolio + package for 300 guests 👇"),
                ("out", "Date held — advance link shared."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "No booking gets lost in a feed again",
            "body": "The highest-value inquiries now get the fastest response, every time.",
            "stat_label": "Response to DM inquiries",
            "stat_from": "Buried",
            "stat_to": "Same day",
        },
    },
    {
        "slug": "gym-fitness-chain",
        "name": "Gym / Fitness Chain",
        "icon": "🏋️",
        "badge": "proposed",
        "use_case": "Trial DMs flood in after a promo. No follow-up happens. Almost none convert to memberships.",
        "solution": "WhatsApp trial-booking flow + GBP",
        "solution_bullets": [
            "A WhatsApp flow that books the trial slot instantly",
            "Automatic follow-up after the trial, not left to memory",
            "Google Business Profile that brings in the next wave of trials",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Trial DMs, zero follow-up",
        "citation": {
            "stat": "Cult.fit — India's largest fitness chain, over 230 centers — is now expanding its franchise model deep into Tier 2 and Tier 3 cities, the exact towns independent gyms used to have entirely to themselves.",
            "source": "Indian Retailer",
            "url": "https://www.indianretailer.com/news/cult-fit-to-build-presence-in-smaller-markets-via-franchise-model.n11772",
        },
        "pain": {
            "eyebrow": "The Moment",
            "title": "50 trial DMs, 2 follow-ups",
            "body": "The promo worked. The follow-up didn't happen, and the trials never convert.",
            "chat": [
                ("in", "Saw your offer, want to try a free class."),
                ("meta", "No booking, no follow-up · lead goes cold"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Trial booked, follow-up automatic",
            "body": "The slot books itself in chat, and a follow-up message goes out right after class.",
            "chat": [
                ("in", "Want to try a free class."),
                ("out", "Booked! Monday 7am, Trainer Rahul 👇"),
                ("out", "How was the class? Here's your membership offer."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Every trial, actually followed up",
            "body": "The promo's real ROI shows up when trials convert instead of going quiet.",
            "stat_label": "Trial → membership follow-up",
            "stat_from": "~4%",
            "stat_to": "100% contacted",
        },
    },
    {
        "slug": "ca-legal-firm",
        "name": "CA / Legal Firm",
        "icon": "⚖️",
        "badge": "proposed",
        "use_case": "No real online presence. The firm loses the client to whoever actually shows up in search.",
        "solution": "Credibility site + WhatsApp consult booking",
        "solution_bullets": [
            "A credibility-first site: expertise, track record, clear services",
            "WhatsApp consult booking so inquiries convert to meetings",
            "Findable when a prospective client actually searches",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Invisible in search results",
        "citation": {
            "stat": "Online compliance platforms now cover everything from GST to ITR filing end to end. When a prospective client can compare a dozen options without leaving their chat app, a firm that doesn't show up online isn't losing on price — it's simply not in the running.",
            "source": "Jurishour — CA Firms & Compliance Platforms in India",
            "url": "https://www.jurishour.in/columns/20-ca-firms-compliance-platforms-working-pan-india/",
        },
        "pain": {
            "eyebrow": "The Moment",
            "title": "Searched, and not found",
            "body": "A prospective client searches “CA near me.” Three other firms show up. This one doesn't.",
            "chat": [
                ("meta", "Google search — firm not listed, not found"),
                ("in", "Went with the firm that came up first."),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Found, then booked",
            "body": "A credibility site and WhatsApp booking turn a search result into a consult.",
            "chat": [
                ("in", "Need help with GST filing, can we talk?"),
                ("out", "Sure — here's our availability, pick a slot 👇"),
                ("out", "Consult confirmed for Wednesday 4pm."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Search becomes a client pipeline",
            "body": "Visibility plus a booking path turns organic search into steady consult volume.",
            "stat_label": "Found in search",
            "stat_from": "Not listed",
            "stat_to": "Top results",
        },
    },
    {
        "slug": "interior-designer",
        "name": "Interior Designer",
        "icon": "🎨",
        "badge": "proposed",
        "use_case": "The reel gets thousands of views. None of them turn into an actual consult booking.",
        "solution": "Case-study portfolio + WhatsApp consult booking",
        "solution_bullets": [
            "A case-study portfolio that proves the work behind the reels",
            "WhatsApp consult booking right where the interest already is",
            "Views convert to conversations, not just likes",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Reel views, zero consult bookings",
        "pain": {
            "eyebrow": "The Moment",
            "title": "10,000 views, 0 bookings",
            "body": "The reel goes semi-viral. There's no clear next step for someone who wants this for their own home.",
            "chat": [
                ("meta", "10.2k views · 340 likes · 0 DMs converted"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "From view to booked consult",
            "body": "A case-study portfolio and WhatsApp booking turn admiration into an actual project.",
            "chat": [
                ("in", "Loved this design! Do you take on 2BHK projects?"),
                ("out", "Yes! Here's similar work + booking link for a consult 👇"),
                ("out", "Consult booked — site visit next week."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Content finally pays for itself",
            "body": "The same reach now converts into real project pipeline, not just engagement.",
            "stat_label": "Views → consult bookings",
            "stat_from": "0%",
            "stat_to": "Tracked & converting",
        },
    },
    {
        "slug": "retail-store",
        "name": "Retail Store (Kirana / General)",
        "icon": "🛒",
        "badge": "proposed",
        "use_case": "A regular customer can't make it to the store today. There's no way to order from home tied to what's actually in stock — so they open Blinkit instead, and the store never even knows it lost the sale.",
        "solution": "WhatsApp catalog + ordering, tied to real inventory",
        "solution_bullets": [
            "A live WhatsApp catalog tied to actual stock — no promising what's not on the shelf",
            "Order + pay in the same chat, pickup or local delivery either way",
            "Keeps the store's real edge — trust, khata credit, zero delivery markup — while matching quick-commerce convenience",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "No home-ordering tied to real stock",
        "citation": {
            "stat": "Nearly 80% of consumers have shifted at least a quarter of their grocery spending to quick-commerce apps, and over 2 lakh kirana stores closed in a single year — yet local stores still hold 88% of India's retail food market on trust, credit, and zero delivery fees alone.",
            "source": "Outlook Business, citing AICPDF",
            "url": "https://www.outlookbusiness.com/explainers/kirana-stores-are-losing-the-battle-against-zepto-blinkit-and-instamart",
        },
        "pain": {
            "eyebrow": "The Moment",
            "title": "Can't come in today — orders from Blinkit instead",
            "body": "A loyal customer needs 6 items tonight. The store doesn't answer WhatsApp with real stock, so the order goes to an app instead — and the store never finds out.",
            "chat": [
                ("in", "Do you have atta, eggs and milk right now? Can someone drop it?"),
                ("meta", "No reply · customer orders on Blinkit in 9 minutes"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Same store, same trust, now open from home",
            "body": "The exact stock on the shelf shows up in WhatsApp. Order, pay, and it's on the way — from the store that already knows them.",
            "chat": [
                ("in", "Do you have atta, eggs and milk right now?"),
                ("out", "Yes, all in stock! ₹410 total — pay here or add to khata 👇"),
                ("out", "Packed — out for delivery, 20 mins."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "The convenience edge, without losing the store's edge",
            "body": "Quick-commerce wins on convenience alone. This closes that one gap — while keeping the trust and credit a delivery app can't offer.",
            "stat_label": "Home-bound orders",
            "stat_from": "Lost to apps",
            "stat_to": "Kept in-store",
        },
    },
    {
        "slug": "automobile-showroom",
        "name": "Automobile Showroom",
        "icon": "🚗",
        "badge": "proposed",
        "use_case": "A walk-in asks about a test drive on Instagram. By the time someone replies, they've already booked one at the showroom down the road.",
        "solution": "WhatsApp test-drive booking + service reminders",
        "solution_bullets": [
            "Test-drive slots booked straight from any inquiry, no back-and-forth",
            "Automatic service-due and insurance-renewal reminders on WhatsApp",
            "Every walk-in and DM tracked, not just the ones someone remembered to note down",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Test-drive inquiry, no slot booked",
        "pain": {
            "eyebrow": "The Moment",
            "title": "Interested, then gone in a day",
            "body": "The inquiry is real. Nobody follows up fast enough, and the next showroom does.",
            "chat": [
                ("in", "Can I test drive the new model this weekend?"),
                ("meta", "Seen · no slot offered · booked elsewhere"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Slot booked before they close the app",
            "body": "The test drive gets scheduled in the same chat the inquiry came in on.",
            "chat": [
                ("in", "Can I test drive the new model this weekend?"),
                ("out", "Sure! Saturday 11am or 4pm — which works? 👇"),
                ("out", "Booked for 11am. See you at the showroom!"),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "From one sale to a service relationship",
            "body": "Service and renewal reminders keep the customer coming back long after the sale.",
            "stat_label": "Test-drive inquiries booked",
            "stat_from": "Hit or miss",
            "stat_to": "Same chat, same visit",
        },
    },
    {
        "slug": "building-materials-showroom",
        "name": "Building Materials / Tiles Showroom",
        "icon": "🧱",
        "badge": "proposed",
        "use_case": "A site visit needs tile samples and a quick quote. The showroom takes days to send either, so the contractor buys from whoever answers first.",
        "solution": "WhatsApp catalog + sample request + fast quote",
        "solution_bullets": [
            "A browsable catalog so contractors can shortlist before they even call",
            "Sample requests routed straight to WhatsApp, not lost in a register",
            "Quote templates so pricing goes out the same day",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "Sample + quote delay loses the order",
        "pain": {
            "eyebrow": "The Moment",
            "title": "Samples took 3 days. Too late.",
            "body": "The contractor needed to decide this week. By the time the sample arrived, the order was placed elsewhere.",
            "chat": [
                ("in", "Need tile samples + quote for a 2000 sqft site, urgent."),
                ("meta", "Samples sent 3 days later · order already placed"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Catalog first, samples same day",
            "body": "The contractor browses, requests samples, and gets a quote — all inside WhatsApp, same day.",
            "chat": [
                ("in", "Need tile samples + quote for a 2000 sqft site, urgent."),
                ("out", "Here's our catalog — shortlist and we'll courier samples today 👇"),
                ("out", "Quote attached, valid 7 days."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Speed wins contractor loyalty",
            "body": "Contractors return to whoever quotes fastest — that's now the default here.",
            "stat_label": "Sample-to-quote time",
            "stat_from": "3 days",
            "stat_to": "Same day",
        },
    },
    {
        "slug": "wholesale-distributor",
        "name": "Wholesale Distributor",
        "icon": "📦",
        "badge": "proposed",
        "use_case": "A retailer wants to reorder stock. There's no easy channel to do it, so they call a competing distributor who makes it simpler.",
        "solution": "WhatsApp reorder catalog + repeat-purchase reminders",
        "solution_bullets": [
            "Retailers reorder by browsing a live catalog on WhatsApp, no phone tag",
            "Automatic reorder nudges timed to each retailer's typical cycle",
            "Every inquiry and repeat order tracked in one place",
        ],
        "starts_at": "₹2,999/mo",
        "leak_label": "No easy reorder channel",
        "pain": {
            "eyebrow": "The Moment",
            "title": "Reordering is harder than it should be",
            "body": "A retailer wants to restock. Calling, waiting on hold, and reading out a list by hand is enough friction to make them call someone else.",
            "chat": [
                ("in", "Need to reorder — can I get the list processed today?"),
                ("meta", "Call unanswered · retailer orders from another distributor"),
            ],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix",
            "title": "Reorder in one WhatsApp message",
            "body": "The retailer picks from a live catalog and the order is confirmed the same day.",
            "chat": [
                ("in", "Need to reorder my usual list."),
                ("out", "Here's your usual order — confirm and it ships today 👇"),
                ("out", "Order confirmed, dispatched."),
            ],
            "accent": "green",
        },
        "growth": {
            "eyebrow": "The Growth",
            "title": "Reorders that happen on their own",
            "body": "Timed nudges mean retailers restock before they even think to call someone else.",
            "stat_label": "Reorder friction",
            "stat_from": "Phone tag",
            "stat_to": "One tap",
        },
    },
]

# ------------------------------------------------------------------
# MODULES — reusable automation add-ons, shared across industries.
# This is what keeps the economics honest: the same n8n-style workflow
# gets adapted per client rather than built from scratch each time.
# effort: "quick" (~2 days to adapt + ship) or "advanced" (~1-2 weeks,
# usually because it touches a live data source like inventory).
# ------------------------------------------------------------------
MODULES = [
    {
        "id": "invoice-reminder",
        "agentic": False,
        "name": "Invoice + Payment Reminders",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "Invoice auto-sent on order/booking, then tiered WhatsApp reminders at 7/14/30 days overdue.",
        "industries": ["export-trading", "b2b-manufacturer", "wholesale-distributor", "interior-designer",
                        "wedding-planner-banquet", "ca-legal-firm", "building-materials-showroom", "real-estate-developer"],
        "pain": {
            "eyebrow": "The Moment", "title": "The invoice went out. The payment didn't.",
            "body": "No one has time to chase every unpaid invoice by hand — so most don't get chased at all.",
            "chat": [("meta", "Invoice #2291 · 21 days overdue · no follow-up sent")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "The reminder sends itself",
            "body": "A WhatsApp nudge goes out automatically at 7, 14, and 30 days — polite, on time, every time.",
            "chat": [
                ("out", "Hi! Friendly reminder — Invoice #2291 (₹18,400) is due. Pay here 👇"),
                ("in", "Sorry, missed this — paying now."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Cash stuck in receivables, freed up",
                    "body": "Nobody spends an afternoon chasing payments anymore — the system already did.",
                    "stat_label": "Average days to collect", "stat_from": "21+ days", "stat_to": "Under 10"},
    },
    {
        "id": "payment-reconciliation",
        "agentic": False,
        "name": "Payment Reconciliation",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "Bank statement and invoice/fee records matched automatically — mismatches flagged, not hunted for.",
        "industries": ["coaching-institute", "gym-fitness-chain", "private-school", "diagnostic-lab", "wholesale-distributor"],
        "pain": {
            "eyebrow": "The Moment", "title": "Whose payment is this, again?",
            "body": "A bank credit shows up. Matching it to the right student, member, or invoice eats an afternoon every week.",
            "chat": [("meta", "47 bank entries · 6 hours spent matching manually this month")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Matched the moment it lands",
            "body": "Every payment is matched against open dues automatically — only real mismatches need a human look.",
            "chat": [
                ("out", "₹4,500 credit matched to Rohan Sharma — March fee, marked paid ✓"),
                ("out", "⚠️ 1 unmatched entry flagged for review."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Hours back, every single week",
                    "body": "Reconciliation stops being a chore that eats a weekly afternoon.",
                    "stat_label": "Time spent matching payments", "stat_from": "Hours weekly", "stat_to": "Minutes"},
    },
    {
        "id": "booking-reminder",
        "agentic": False,
        "name": "Booking Confirmation + No-Show Reminder",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "Every booking auto-confirmed, with a WhatsApp reminder before the slot so no-shows drop.",
        "industries": ["hospital", "diagnostic-lab", "ca-legal-firm", "interior-designer", "gym-fitness-chain", "automobile-showroom"],
        "pain": {
            "eyebrow": "The Moment", "title": "Booked, then forgotten",
            "body": "A slot gets booked. Nobody reminds the customer, so a chunk of appointments become no-shows.",
            "chat": [("meta", "Appointment booked 9 days ago · no reminder sent · no-show")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "A nudge, right before the slot",
            "body": "A confirmation goes out instantly, then a reminder the day before — automatically.",
            "chat": [
                ("out", "Booked! Thursday 4:30pm, confirmed ✓"),
                ("out", "Reminder: your appointment is tomorrow at 4:30pm."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Fewer empty slots, more kept appointments",
                    "body": "The calendar stops leaking time to forgetfulness.",
                    "stat_label": "No-show rate", "stat_from": "1 in 5", "stat_to": "Rare"},
    },
    {
        "id": "claim-email-dispatch",
        "agentic": False,
        "name": "Claim / Document Auto-Email Dispatch",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "A claim or document summary is auto-generated and emailed to the right address the moment it's ready — with WhatsApp status updates back to the customer. No payer-system integration, just a fast, reliable send.",
        "industries": ["hospital", "diagnostic-lab"],
        "pain": {
            "eyebrow": "The Moment", "title": "The claim sits in a drawer",
            "body": "Paperwork for an insurance claim is ready. Actually typing, attaching, and emailing it out gets pushed to \"later.\"",
            "chat": [("meta", "Claim documents ready · 4 days sitting unsent")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Sent the moment it's ready",
            "body": "The claim summary is generated and emailed to the insurer's claims address automatically — the patient gets a WhatsApp update.",
            "chat": [
                ("meta", "Claim #7741 emailed to insurer's claims desk — auto-sent"),
                ("out", "Your claim has been submitted. We'll update you here on status."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Nothing sits in a drawer again",
                    "body": "A same-day send instead of a multi-day backlog — no new integration required.",
                    "stat_label": "Time to dispatch a claim", "stat_from": "Days", "stat_to": "Minutes"},
    },
    {
        "id": "review-reply",
        "agentic": True,
        "name": "Review Request + AI-Drafted Reply",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "A WhatsApp review request goes out after service; AI drafts a reply to every Google review for a quick human approve-and-post.",
        "industries": ["gym-fitness-chain", "diagnostic-lab", "interior-designer", "wedding-planner-banquet", "retail-store", "automobile-showroom"],
        "pain": {
            "eyebrow": "The Moment", "title": "Happy customers, no reviews",
            "body": "Most people don't leave a review unless asked — and nobody has time to ask, or to reply to the ones that come in.",
            "chat": [("meta", "3 new Google reviews · 0 replies in 2 months")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Asked at the right moment, replied to fast",
            "body": "A review request goes out right after service, and every incoming review gets an AI-drafted reply ready to approve.",
            "chat": [
                ("out", "Thanks for visiting today! Mind leaving us a quick review? 👇"),
                ("meta", "New 5★ review — reply drafted, ready to approve"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "A steady stream of fresh, answered reviews",
                    "body": "Review volume and response rate both move — which is what actually moves local search ranking.",
                    "stat_label": "Reviews replied to", "stat_from": "Rarely", "stat_to": "Every one"},
    },
    {
        "id": "stock-check-reserve",
        "agentic": False,
        "name": "Stock Check-and-Reserve",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Customer asks if something's in stock on WhatsApp — the bot checks the real inventory sheet and lets them reserve it.",
        "industries": ["retail-store", "building-materials-showroom", "wholesale-distributor"],
        "pain": {
            "eyebrow": "The Moment", "title": "\"Is it in stock?\" — nobody knows without a call",
            "body": "Checking stock means someone walking to the shelf or calling around. Most customers don't wait.",
            "chat": [("in", "Is the 10kg bag in stock right now?"), ("meta", "No answer · customer buys elsewhere")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Checked and reserved, instantly",
            "body": "The chat checks the live inventory sheet and holds the item the moment they confirm.",
            "chat": [
                ("in", "Is the 10kg bag in stock right now?"),
                ("out", "Yes, 6 left! Reserve one? 👇"),
                ("out", "Reserved for you — ready for pickup."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Stock questions become sales, not guesses",
                    "body": "Real-time stock answers keep the customer here instead of one tap away from an app.",
                    "stat_label": "Stock inquiries answered instantly", "stat_from": "Only if someone's free", "stat_to": "Always"},
    },
    {
        "id": "reorder-nudge",
        "agentic": False,
        "name": "Reorder / Repeat-Purchase Nudge",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "A WhatsApp nudge times itself to each customer's usual reorder cycle, before they think to call someone else.",
        "industries": ["wholesale-distributor", "retail-store", "building-materials-showroom"],
        "pain": {
            "eyebrow": "The Moment", "title": "They forgot to reorder — from you",
            "body": "A regular buyer runs low and just orders from whoever's easiest to reach that day. It isn't always this business.",
            "chat": [("meta", "Regular buyer's usual 30-day cycle passed — no nudge sent")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "A nudge, right on cycle",
            "body": "A WhatsApp reminder goes out timed to their usual reorder pattern, with the usual order pre-filled.",
            "chat": [
                ("out", "Running low on your usual order? Reorder in one tap 👇"),
                ("in", "Yes please, same as last time."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Repeat business that doesn't rely on memory",
                    "body": "The reorder happens because the system remembered — not because the customer did.",
                    "stat_label": "Repeat orders captured", "stat_from": "Whoever remembers", "stat_to": "On cycle, automatically"},
    },
    {
        "id": "lead-qualification",
        "agentic": True,
        "name": "Lead Qualification & Scoring Agent",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Asks 2-3 quick questions automatically, scores the inquiry hot/warm/cold, and routes only the hot ones straight to you.",
        "industries": ["real-estate-developer", "b2b-manufacturer", "interior-designer", "ca-legal-firm", "wholesale-distributor", "automobile-showroom"],
        "pain": {
            "eyebrow": "The Moment", "title": "20 inquiries, and no way to tell which 3 matter",
            "body": "Every inquiry looks the same at first glance. Time goes to whoever asked first, not whoever's actually ready to buy.",
            "chat": [("meta", "20 inquiries this week · 3 were serious buyers · found out after calling all 20")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Scored before it reaches you",
            "body": "A few quick questions score the inquiry automatically — only the hot ones land in your WhatsApp.",
            "chat": [
                ("in", "Interested in the 3BHK, what's the budget range?"),
                ("out", "Great! Quick check — are you looking to buy in the next 3 months?"),
                ("meta", "🔥 Scored HOT — routed to owner instantly"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Time goes where the deal is",
                    "body": "The serious buyers stop getting lost in the same pile as the window-shoppers.",
                    "stat_label": "Time spent on low-intent leads", "stat_from": "Hours daily", "stat_to": "Only hot leads"},
    },
    {
        "id": "objection-handling",
        "agentic": True,
        "name": "FAQ + Objection-Handling Agent",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "Answers the same 15-20 questions and objections instantly and consistently — escalates only what's genuinely new.",
        "industries": ["coaching-institute", "gym-fitness-chain", "interior-designer", "ca-legal-firm", "diagnostic-lab"],
        "pain": {
            "eyebrow": "The Moment", "title": "The same question, for the 20th time today",
            "body": "\"Is it safe\", \"what's included\", \"can I pay in installments\" — answering these all day leaves no time for anything else, and slow answers lose the sale.",
            "chat": [("meta", "Same 5 questions asked 20+ times this week, answered manually each time")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Answered instantly, every time",
            "body": "Common questions and objections get an instant, consistent answer. Genuinely new questions still reach a human.",
            "chat": [
                ("in", "Can I pay in installments?"),
                ("out", "Yes! 3 easy installments, no extra charge. Want me to set that up? 👇"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Time freed up for the questions that actually need a human",
                    "body": "The repetitive 80% stops eating the day.",
                    "stat_label": "Repetitive questions handled by a human", "stat_from": "Every one", "stat_to": "Only the new ones"},
    },
    {
        "id": "negative-review-recovery",
        "agentic": True,
        "name": "Negative Review Alert + Recovery Agent",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "Flags a bad review the moment it lands, with a drafted apology and a service-recovery offer ready to approve within the hour.",
        "industries": ["gym-fitness-chain", "diagnostic-lab", "wedding-planner-banquet", "retail-store", "automobile-showroom", "interior-designer"],
        "pain": {
            "eyebrow": "The Moment", "title": "A bad review, sitting there for days",
            "body": "By the time anyone notices and responds, the next ten prospects have already read it — unanswered.",
            "chat": [("meta", "1★ review posted 4 days ago · still no reply · visible to every new visitor")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Flagged and drafted within minutes",
            "body": "The moment a negative review lands, an alert goes out with a drafted, empathetic reply and a recovery offer ready to send.",
            "chat": [
                ("meta", "⚠️ New 1★ review — reply + recovery offer drafted, ready to approve"),
                ("out", "We're sorry we missed the mark — we'd like to make it right. Can we call you?"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Damage caught before it compounds",
                    "body": "A fast, human response to a bad review often does more for trust than a string of good ones.",
                    "stat_label": "Time to respond to a bad review", "stat_from": "Days, if ever", "stat_to": "Same hour"},
    },
    {
        "id": "win-back",
        "agentic": False,
        "name": "Abandoned-Inquiry Win-Back Agent",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Re-engages a promising inquiry automatically after a few days of silence, with a fresh nudge instead of writing it off.",
        "industries": ["real-estate-developer", "interior-designer", "wedding-planner-banquet", "coaching-institute", "automobile-showroom"],
        "pain": {
            "eyebrow": "The Moment", "title": "Interested, then silent — and forgotten",
            "body": "The conversation went well, then stopped. Nobody follows up a second time, so it's quietly written off.",
            "chat": [("meta", "Last message 6 days ago · no follow-up sent · lead effectively dead")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "A second chance, sent automatically",
            "body": "After a few days of silence, a re-engagement message goes out on its own — sometimes that's all it takes.",
            "chat": [
                ("out", "Still thinking it over? Happy to answer anything, or share a quick offer 👇"),
                ("in", "Actually yes, I got busy — let's continue."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Leads that would've just gone cold",
                    "body": "A fair share of \"dead\" inquiries were never actually dead — just unattended.",
                    "stat_label": "Cold leads re-engaged", "stat_from": "Written off", "stat_to": "Given a second chance"},
    },
    {
        "id": "seo-content-agent",
        "agentic": True,
        "name": "AI Local-SEO Content Agent",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Drafts a weekly local-SEO blog or Google Business post automatically — a 2-minute human review is all it needs before publishing.",
        "industries": ["ca-legal-firm", "interior-designer", "diagnostic-lab", "gym-fitness-chain", "coaching-institute", "retail-store"],
        "pain": {
            "eyebrow": "The Moment", "title": "Nobody has time to write a blog post",
            "body": "Fresh content is what search ranking actually rewards. It also never happens, because nobody has a spare afternoon.",
            "chat": [("meta", "Last blog/GBP post: 3 months ago · search visibility quietly declining")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "A draft, ready every week",
            "body": "A relevant local post gets drafted automatically — approve, tweak if needed, publish.",
            "chat": [
                ("meta", "This week's draft ready: \"5 Signs You Need [Service] Before Monsoon\""),
                ("out", "Reviewed and published ✓"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Consistency, without the time cost",
                    "body": "Search ranking rewards a business that keeps showing up — this makes that the default, not the exception.",
                    "stat_label": "Fresh content published", "stat_from": "Whenever someone remembers", "stat_to": "Every week"},
    },
    {
        "id": "missed-call-winback",
        "agentic": False,
        "name": "Missed-Call Instant Win-Back Agent",
        "effort": "quick",
        "badge": "proposed",
        "blurb": "The moment a call is missed, an automatic WhatsApp picks the conversation back up — before the caller tries someone else.",
        "industries": ["hospital", "diagnostic-lab", "ca-legal-firm", "automobile-showroom", "retail-store", "gym-fitness-chain"],
        "pain": {
            "eyebrow": "The Moment", "title": "A missed call is a lost inquiry",
            "body": "Nobody calls back in time, if at all — and the caller has usually already tried the next number on the list.",
            "chat": [("meta", "Missed call · 14:32 · no callback · number not seen again")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Picked up on WhatsApp, instantly",
            "body": "The moment a call is missed, a WhatsApp message goes out automatically — the conversation doesn't just die.",
            "chat": [
                ("meta", "Missed call · 14:32"),
                ("out", "Sorry we missed your call! How can we help — want us to call you back?"),
                ("in", "Yes please, in 10 mins."),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Every missed call, still a live inquiry",
                    "body": "A missed call stops being an automatic loss.",
                    "stat_label": "Missed calls followed up", "stat_from": "Rarely", "stat_to": "Every one, instantly"},
    },
    {
        "id": "quotation-drafting",
        "agentic": True,
        "name": "AI Quotation Drafting Agent",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Turns a rough customer requirement into a properly formatted, ready-to-send quote — the owner just approves and sends.",
        "industries": ["b2b-manufacturer", "export-trading", "interior-designer", "building-materials-showroom", "wholesale-distributor"],
        "pain": {
            "eyebrow": "The Moment", "title": "A quote that takes 30 minutes to type up",
            "body": "Turning a customer's rough requirement into a clean, formatted quote is slow enough that it often goes out a day late.",
            "chat": [("meta", "Requirement received 9am · quote finally sent 6pm · buyer already compared elsewhere")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "Drafted the moment the requirement lands",
            "body": "The raw requirement is turned into a formatted quote draft automatically — just review and send.",
            "chat": [
                ("in", "Need 2000 units, spec attached, budget-conscious."),
                ("meta", "Quote draft ready: 2000 units, tiered pricing, valid 7 days"),
                ("out", "Quote sent ✓"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Quotes that go out same-day, by default",
                    "body": "Speed becomes the default instead of the exception that happens when someone has spare time.",
                    "stat_label": "Time to draft a quote", "stat_from": "30+ minutes", "stat_to": "Under 2 minutes"},
    },
    {
        "id": "competitor-price-watch",
        "agentic": False,
        "name": "Competitor Price-Watch Alert Agent",
        "effort": "advanced",
        "badge": "proposed",
        "blurb": "Checks competitors' public listings and prices periodically, and alerts the owner the moment something changes.",
        "industries": ["retail-store", "wholesale-distributor", "automobile-showroom", "building-materials-showroom", "gym-fitness-chain"],
        "pain": {
            "eyebrow": "The Moment", "title": "The competitor moved, and nobody noticed",
            "body": "A nearby competitor quietly drops a price or launches an offer. Customers notice immediately. The business finds out weeks later, if at all.",
            "chat": [("meta", "Competitor offer live 3 weeks · noticed only after regular customers started asking about it")],
            "accent": "red",
        },
        "fix": {
            "eyebrow": "The Fix", "title": "An alert, the same day it happens",
            "body": "Public listings and prices are checked automatically — a change triggers an alert immediately.",
            "chat": [
                ("meta", "⚠️ Competitor dropped price on their listing — alert sent"),
                ("out", "Heads up: [Competitor] is now offering 10% off. Want to respond?"),
            ],
            "accent": "green",
        },
        "growth": {"eyebrow": "The Growth", "title": "Reacting same-day instead of weeks late",
                    "body": "Being the last to know stops being the default.",
                    "stat_label": "Time to notice a competitor's price move", "stat_from": "Weeks, if ever", "stat_to": "Same day"},
    },
]

# Curated, capped secondary automations shown per Industry page + Custom Pack
# (kept to 2-3 per industry — deliberately narrower than each module's
# broader `industries` tag list above, which is used for Demos search/filter).
INDUSTRY_MODULES = {
    "export-trading": ["invoice-reminder"],
    "hospital": ["booking-reminder", "claim-email-dispatch"],
    "coaching-institute": ["payment-reconciliation"],
    "real-estate-developer": ["invoice-reminder"],
    "b2b-manufacturer": ["invoice-reminder"],
    "private-school": ["payment-reconciliation"],
    "diagnostic-lab": ["booking-reminder", "claim-email-dispatch"],
    "wedding-planner-banquet": ["invoice-reminder", "review-reply"],
    "gym-fitness-chain": ["payment-reconciliation", "review-reply"],
    "ca-legal-firm": ["invoice-reminder", "booking-reminder"],
    "interior-designer": ["invoice-reminder", "booking-reminder"],
    "retail-store": ["stock-check-reserve", "reorder-nudge", "review-reply"],
    "automobile-showroom": ["booking-reminder", "review-reply"],
    "building-materials-showroom": ["invoice-reminder", "stock-check-reserve"],
    "wholesale-distributor": ["invoice-reminder", "payment-reconciliation", "reorder-nudge"],
}

# ------------------------------------------------------------------
# FLAGSHIP — the negotiation/instant-response agent. Bigger than a
# standard module (4 scenes, not a pain/fix pair), gets its own full
# cinematic demo page and top billing on Agentic Use Cases.
# ------------------------------------------------------------------
NEGOTIATION_AGENT = {
    "id": "negotiation-agent",
    "name": "Instant-Response + Negotiation Agent",
    "badge": "proposed",
    "agentic": True,
    "blurb": "From being the listing that actually gets tapped, to an instant reply, a quote, a negotiation that matches a named competitor's price, a payment link close, and the follow-up + referral that brings the next order.",
    "stages": [
        {
            "kind": "search", "eyebrow": "The Moment", "title": "Found on Google. Skipped in two seconds.",
            "body": "A customer searches and sees 4-5 businesses. The ones without a complete profile — no posts, no website, no way to message — get scrolled past without a second thought.",
            "accent": "red",
            "query": "AC repair near me",
            "winner_idx": 0,
            "results": [
                {"name": "CoolBreeze AC Repair", "rating": 4.5, "reviews": 180, "distance": "0.9 km", "complete": True},
                {"name": "Sharma AC Services", "rating": 4.0, "reviews": 15, "distance": "1.1 km", "complete": False},
                {"name": "Patil Air Solutions", "rating": 3.8, "reviews": 40, "distance": "1.6 km", "complete": True},
                {"name": "Fresh Air Cooling", "rating": 3.6, "reviews": 10, "distance": "2.0 km", "complete": False},
            ],
        },
        {
            "kind": "search", "eyebrow": "The Fix — Step 1", "title": "A profile that actually gets chosen",
            "body": "Posts, a website link, and a WhatsApp button turn a listing into the obvious choice — before a single message is even sent.",
            "accent": "green",
            "query": "AC repair near me",
            "winner_idx": 1,
            "results": [
                {"name": "CoolBreeze AC Repair", "rating": 4.5, "reviews": 180, "distance": "0.9 km", "complete": True},
                {"name": "Sharma AC Services", "rating": 4.0, "reviews": 15, "distance": "1.1 km", "complete": True},
                {"name": "Patil Air Solutions", "rating": 3.8, "reviews": 40, "distance": "1.6 km", "complete": True},
                {"name": "Fresh Air Cooling", "rating": 3.6, "reviews": 10, "distance": "2.0 km", "complete": False},
            ],
        },
        {
            "kind": "chat_screen", "eyebrow": "The Fix — Step 2", "title": "Replied before they could message anyone else",
            "body": "The inquiry gets an instant, pre-drafted response — and a smart follow-up question, not just a generic \"thanks for reaching out.\"",
            "accent": "green", "contact": "Vikram Joshi", "status": "Online",
            "chat": [
                ("in", "Hi, need AC repair, what's the process?"),
                ("out", "Hi! Happy to help — is it a split AC or window unit, and what's the issue?"),
                ("in", "Split AC, not cooling properly."),
            ],
        },
        {
            "kind": "chat_screen", "eyebrow": "The Fix — Step 3", "title": "A quote, not a guessing game",
            "body": "Enough detail is already in hand to send a real quote — not a vague \"we'll get back to you.\"",
            "accent": "green", "contact": "Vikram Joshi", "status": "Online",
            "chat": [
                ("out", "Got it — gas refill + service, ₹899 total. Technician can come today 👇"),
            ],
        },
        {
            "kind": "chat_screen", "eyebrow": "The Fix — Step 4", "title": "When they want to negotiate, it doesn't lose the deal",
            "body": "Most owners lose the back-and-forth to whoever's more flexible on a call. The agent handles it instead — confidently, within limits set in advance.",
            "accent": "green", "contact": "Vikram Joshi", "status": "Online",
            "chat": [
                ("in", "₹899 is a bit much, can you do better?"),
                ("out", "I can help with that! Did another provider quote you something?"),
                ("in", "Yeah, CoolBreeze quoted ₹699."),
                ("out", "We'll match that at ₹699 — and ours includes a 30-day warranty. Shall I book it?"),
                ("in", "Deal, book it."),
            ],
        },
        {
            "kind": "payment", "eyebrow": "The Fix — Step 5", "title": "A payment link closes more than a phone call",
            "body": "Once it's agreed, a payment link goes out immediately — people commit to a link faster than they commit out loud on a call.",
            "accent": "green",
            "business": "Sharma AC Services", "amount": "₹699", "paid": True,
        },
        {
            "kind": "stat", "eyebrow": "The Growth", "title": "One customer becomes many",
            "body": "A follow-up after service brings the next order. A referral offer turns a happy customer into a new one — automatically, every time.",
            "stat_label": "One satisfied customer",
            "stat_from": "One sale, then silence",
            "stat_to": "Repeat orders + referrals",
        },
    ],
}

PRICING_PACKS = [
    {
        "name": "Go Digital Pack",
        "price": "₹2,999/mo",
        "tag": "Entry",
        "includes": ["Google Business Profile setup + optimization", "Business website", "Monthly blog content"],
    },
    {
        "name": "Growth Pack",
        "price": "Contact us for a quote",
        "tag": "Most Popular",
        "includes": ["Everything in Go Digital", "Booking Engine (appointments / visits / trials)"],
    },
    {
        "name": "Expansion Pack",
        "price": "Contact us for a quote",
        "tag": "Scale",
        "includes": ["Everything in Growth", "Automations — invoice generation and more"],
    },
]

CUSTOM_HAVE = ["Already have a website", "Already have a Google Business Profile"]
CUSTOM_ADDONS = [
    "Invoice / quote tool", "WhatsApp reminder tool", "Payment portal",
    "Multilingual add-on", "Google Ads landing page", "Customer database export",
    "WhatsApp broadcast", "Review-reply templates", "Missed-call-to-WhatsApp auto-reply",
]
